### ISSUE TITLE
Is there some  clerical error in the Figure 9(B) of the papers

### ISSUE THREAD

**Issue by Jam-G** [mahmoudnafifi/mixedillWB#2]
The strides of Conv2D in residual, downsampling, and upsampling units  are 2, described in Figure 9(B) .  Are they clerical errors?
I think the residual and upsampling units Conv2d op should be stride=1, and they are 1 in `gridnet.py` really.
Or I have some misunderstanding？

**Comment by mahmoudnafifi** [comment]
Thanks for pointing out this mistake in the figure. Yes it should have stride=1 as written in the code.
