### ISSUE TITLE
How was the GT images created?

### ISSUE THREAD

**Issue by Haoban** [mahmoudnafifi/mixedillWB#3]
Hi Mahmoud,

I have two questions about dataset.

**First one:** 

I am pretty curious about how do you create the GT images. In the paper, you mentioned "each scene has at least two types of
light sources (e.g., indoor and outdoor lighting)". 

And in create GT images part, you claimed "To render the ground-truth images, we set the color temperature of our virtual camera’s WB and all light sources in the scene to 5500 K (i.e., daylight)". Do you mean the indoor and outdoor lighting are the same, that is 5500K? 

**Second one:**

What is the difference between image D_CS and G_AS, G_AS comes from 5500K lightsource and 5500K WB settings. And D_CS has daylight (5500K) light source, and what is the white balance estimation? Does it directly come from camera standard pipeline instead of presetting?

Thanks for answering in advance.

**Comment by mahmoudnafifi** [comment]
Thanks for your questions.

As you mentioned, yes we set all virtual light source to daylight and set the virtual camera WB to the daylight setting.

Please note that images end with D_CS were rendered with daylight WB. That doesn’t necessarily mean the scene has daylight light source. 

All images were rendered using vray virtual camera/rendering. Vray has it is own rendering pipeline that should differ from real camera pipeline.

I hope this answer your questions.

**Comment by Haoban** [comment]
It do help a lot, and thanks for the answer.
