### ISSUE TITLE
Edge-aware smoothing cannot be switched off

### ISSUE THREAD

**Issue by kmilos** [mahmoudnafifi/mixedillWB#5]
Boolean option switches are always set to True by default whenever they're present on the command line, regardless of the specified value, i.e. `--post-process False` has no effect, so the default action has to be changed somehow. See e.g. https://stackoverflow.com/questions/50954491/python-argparse-how-to-pass-false-from-the-command-line

I guess the same goes for `--save-weights` and `--multi-scale` that are bool switches defaulted to True...

**Comment by mahmoudnafifi** [comment]
Thanks for your comment. Yes i know this issue but forgot to fix it. store_true should fix it or setting their default values to false.
