### ISSUE TITLE
about the single-illuminant Cube+ dataset ground trith images

### ISSUE THREAD

**Issue by roger308** [mahmoudnafifi/mixedillWB#8]
Hi ,
thanks for your work in color consistency. I thik it is helpful for me.

But i was encountering some question in your  single-illuminant Cube+ dataset
When i tried to download the single-illuminant Cube+ dataset, i found the resource in ground truth image only given the illuminant estimate (txt) not the images.
Could you release the ground truth image for dowloading,or teaching me how to reconstruct the ground truth image in  single-illuminant Cube+ dataset?

very thanks,

**Comment by roger308** [comment]
Hi ,

Sorry for bothering you again. To ensure a fair comparison of the scores, I would like to inquire about the processing applied to the input image of the single-illuminant Cube+ dataset.
Is the processing similar to the Matlab procedure outlined at https://ipg.fer.hr/ipg/resources/color_constancy? If possible, could you kindly provide me with the download links for the input image and the ground truth image?

I truly appreciate your assistance. Thank you.
Alternatively, you can reach me via email for download links: rogerchen3309@gmail.com

**Comment by mahmoudnafifi** [comment]
Hi, Cube+ was rendered to sRGB using PS to emulate camera non-linear rendering. The ground-truth images were rendered by manually selecting the gray reference point from the calibration object in each image before rendering on PS. You can download this set from [here](https://cvil.eecs.yorku.ca/projects/public_html/sRGB_WB_correction/dataset.html).

**Comment by roger308** [comment]
Hi,
Thanks for your answering.
So,in this paper the table 1 use the render cube+ dataset which contains 10,242 rendered images,right?

![image](https://github.com/mahmoudnafifi/mixedillWB/assets/120006443/57a5b621-908d-43db-b583-1a379615a12a)

thanks a lot,

**Comment by mahmoudnafifi** [comment]
Right.

**Comment by roger308** [comment]
Thanks you!! Very appreciate
