### ISSUE TITLE
about the single-illuminant Cube+ dataset color temperature

### ISSUE THREAD

**Issue by roger308** [mahmoudnafifi/mixedillWB#9]
Hi ,
thanks for your work in color consistency. I thik it is helpful for me.

After read your paper, i think that you use T,D,S &T,D,F,C,S color temperature to test on cube plus dataset.
But when i download the cube+ dataset(10242),i find that the image name  only inclouded(AU,AS,D,F,S,T).
So,i was wondering to know which image setting(AU or AS) you choose to replace with C(cloudy) temperature.

thanks,prof

**Comment by mahmoudnafifi** [comment]
Hi, thanks for your interest in the work. AU and AS refers to "auto correction" (by Photoshop in raw space) and "as shot" (the auto correction by camera in raw space also). For cloudy WB, I believe we rendered sRGB images with cloudy WB preset from raw, but that wasn't added to the rendered Cube set you refer to.

**Comment by roger308** [comment]
Hi Prof, thanks for your responds. I am not sure that in order to test on cube+ dataset 5 wb settings (t,d,s,f,c) score, you using the deepwb pretrain weight to  get only one cloudy setting image(because cube+ have other(d,f,s,t) images or using D setting image with deepwb pretrain weight to get (t,s,f,c) 4 images.

**Comment by mahmoudnafifi** [comment]
To get cloudy WB you can use Photoshop to render cube DNG files with this WB preset. Or as you mentioned to use deepWB to emulate this preset.

**Comment by roger308** [comment]
Ok,i see.THanks for your answering.
